name: Priot Site
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/071144d9-1def-4fe5-a751-6cd98d93b5ca.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9f8af0af-bd9b-4fce-8864-d6e073abb810.jpg
layout_spectrum: 0.08398724576882502
typography_spectrum: 0.16178662623453996
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.6030396229790358
  lightness: 0.3440385069113483
  saturation: 0.22449792055947945
  rhythmicContrast: 0.7010322466778504
title: "Сайт Прёт \uD83C\uDF52 Priot Site"
description: "Наташа Блинова, Пётр Талалай и их Дуэт, Трио и Ансамбль Прёт \uD83C\uDF3C Natasha Blinova, Piotr Talalay and their Priot Duo, Priot Trio and Priot Ensemble"
author:
  name: "Сайт сей изготовлен и поддерживается Талалаем с любовью в Тропарёво-Никулино \uD83D\uDD78 Made and updating by @talalife with Love in Tropariovo-Nikulino"
  url: 'https://t.me/talalife'
  email: talalife@gmail.com
content_rating:
  adult: false
navigation:
  - name: 'Альбом: Настоящее | Present Continuous'
    id: 57f14cc9-82b0-41e0-bb9e-0c43df24ff96
    type: content
  - name: Контакты | Contact
    id: b9fd7a51-53f0-47de-af34-79525bde8cd4
    type: content
  - name: Музыка
    id: 57f14cc9-82b0-41e0-bb9e-0c43df24ff96
    type: content
  - name: Фото
    id: 283fc778-778b-4b1d-9adc-4c6914ebb300
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FZ7cwgbjFiEE%3Fstart%3D91%26feature%3Doembed%26start%3D91&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZ7cwgbjFiEE&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FZ7cwgbjFiEE%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': VideoObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'http://youtu.be/Z7cwgbjFiEE?t=1m31s'
      keywords:
        - priot
        - priot trio
        - ансамбль прет
        - прёт
        - psychedelic
        - voice
        - moscow
        - dance
        - jazz
        - vocal
        - blinova
        - блинова
      title: Priot Trio - All The Things You Are (Live)
      publisher:
        name: YouTube
        domain: youtu.be
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
      author:
        - name: Piotr Talalay
          url: 'https://www.youtube.com/user/talalife'
          avatar: {}
      starred: false
      description: Live at The Worker And The Kolkhoz Woman. August 2015
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
