layout_spectrum: 0.08398724576882502
typography_spectrum: 0.16178662623453996
color:
  lightness: 0.3440385069113483
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  saturation: 0.22449792055947945
  brandStrength: 0.6030396229790358
  rhythmicContrast: 0.7010322466778504
name: Priot Site
analytics: {}
github: true
description: "Наташа Блинова, Пётр Талалай и их Дуэт, Трио и Ансамбль Прёт \uD83C\uDF3C Natasha Blinova, Piotr Talalay and their Priot Duo, Priot Trio and Priot Ensemble"
author:
  name: "Сайт сей изготовлен и поддерживается Талалаем с любовью в Тропарёво-Никулино \uD83D\uDD78 Made and updating by @talalife with Love in Tropariovo-Nikulino"
  url: 'https://t.me/talalife'
  email: talalife@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FZ7cwgbjFiEE%3Fstart%3D91%26feature%3Doembed%26start%3D91&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZ7cwgbjFiEE&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FZ7cwgbjFiEE%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Piotr Talalay
          url: 'https://www.youtube.com/user/talalife'
          avatar: {}
      '@context': 'http://schema.org'
      keywords:
        - priot
        - priot trio
        - ансамбль прет
        - прёт
        - psychedelic
        - voice
        - moscow
        - dance
        - jazz
        - vocal
        - blinova
        - блинова
      '@type': VideoObject
      title: Priot Trio - All The Things You Are (Live)
      isBasedOnUrl: 'http://youtu.be/Z7cwgbjFiEE?t=1m31s'
      publisher:
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        url: 'https://www.youtube.com/'
        name: YouTube
        domain: youtu.be
      description: Live at The Worker And The Kolkhoz Woman. August 2015
      related: []
      app_links:
        - app_store_id: '544007664'
          namespace: ai
          app_name: YouTube
          url: 'vnd.youtube://www.youtube.com/watch?v=Z7cwgbjFiEE&feature=applinks'
          type: ios
        - package: com.google.android.youtube
          app_name: YouTube
          namespace: ai
          url: 'vnd.youtube://www.youtube.com/watch?v=Z7cwgbjFiEE&feature=applinks'
          type: android
        - url: 'https://www.youtube.com/watch?v=Z7cwgbjFiEE&feature=applinks'
          type: web
          namespace: ai
        - id: '544007664'
          namespace: twitter
          url: 'vnd.youtube://www.youtube.com/watch?v=Z7cwgbjFiEE&feature=applinks'
          type: ipad
          name: YouTube
        - id: '544007664'
          namespace: twitter
          url: 'vnd.youtube://www.youtube.com/watch?v=Z7cwgbjFiEE&feature=applinks'
          type: iphone
          name: YouTube
        - id: com.google.android.youtube
          namespace: twitter
          url: 'https://www.youtube.com/watch?v=Z7cwgbjFiEE'
          type: googleplay
          name: YouTube
        - path: http/www.youtube.com/watch?v=Z7cwgbjFiEE
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=Z7cwgbjFiEE
          package: '544007664'
          namespace: google
          type: ios
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: 57f14cc9-82b0-41e0-bb9e-0c43df24ff96
    name: 'Альбом: Настоящее | Present Continuous'
    type: content
  - id: b9fd7a51-53f0-47de-af34-79525bde8cd4
    name: Контакты | Contact
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/071144d9-1def-4fe5-a751-6cd98d93b5ca.jpg
content_rating:
  adult: false
opengraph: {}
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/92f3a04b-877a-49a8-9962-a6d7f91ee145.jpg
title: "Сайт Прёт \uD83C\uDF52 Priot Site"
