name: Priot Site
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/071144d9-1def-4fe5-a751-6cd98d93b5ca.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9f8af0af-bd9b-4fce-8864-d6e073abb810.jpg
layout_spectrum: 0.6198899488088371
typography_spectrum: 0.8680269939372187
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.6023132319917146
  lightness: 0.3408786749832406
  saturation: 0.22483853725190875
  rhythmicContrast: 0.7044196971420125
title: "Сайт Прёт \uD83C\uDF52 Priot Site"
description: "Наташа Блинова, Пётр Талалай и их Дуэт, Трио и Ансамбль Прёт \uD83C\uDF3C Natasha Blinova, Piotr Talalay and their Priot Duo, Priot Trio and Priot Ensemble"
author:
  name: "Сайт сей изготовлен и поддерживается Талалаем с любовью в Тропарёво-Никулино \uD83D\uDD78 Made and updating by @talalife with Love in Tropariovo-Nikulino"
  url: 'https://t.me/talalife'
  email: talalife@gmail.com
content_rating:
  adult: false
navigation:
  - name: Дуэт Прёт | Priot Duo
    id: e9c4b1fc-d4c4-45f7-9b22-14a1b3912fba
    type: content
  - name: Angel Ontalva VS Priot Duo
    id: f8f315f6-8588-4168-8b43-85dae1071f17
    type: content
  - name: Трио Прёт | Priot Trio
    id: 6472be7a-ea61-4c83-9301-bb65f1bb7e66
    type: content
  - name: Ансамбль Прёт | Priot Ensemble
    id: 4068363f-aefb-4907-b34f-2f3939b899d7
    type: content
  - name: Наташа Блинова | Natasha Blinova
    id: 0cbfaf5d-09d3-4b29-961a-44191f0fa7f7
    type: content
  - name: Анхель Онтальва | Angel Ontalva
    id: 21404520-b4eb-4d12-abe4-109897caf8fe
    type: content
  - name: Пётр Талалай | Piotr Talalay
    id: c0fbbd1e-c657-40d7-a71e-337b772a72cb
    type: content
  - name: Музыка | Music
    id: 57f14cc9-82b0-41e0-bb9e-0c43df24ff96
    type: content
  - name: Фото | Photos
    id: 283fc778-778b-4b1d-9adc-4c6914ebb300
    type: content
  - name: Видео | Videos
    id: c6e2a46a-68e0-4b92-8eae-f9f40da70fd7
    type: content
  - name: Контакты | Contacts
    id: b9fd7a51-53f0-47de-af34-79525bde8cd4
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FZ7cwgbjFiEE%3Fstart%3D91%26feature%3Doembed%26start%3D91&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZ7cwgbjFiEE&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FZ7cwgbjFiEE%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': VideoObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'http://youtu.be/Z7cwgbjFiEE?t=1m31s'
      keywords:
        - priot
        - priot trio
        - ансамбль прет
        - прёт
        - psychedelic
        - voice
        - moscow
        - dance
        - jazz
        - vocal
        - blinova
        - блинова
      title: Priot Trio - All The Things You Are (Live)
      publisher:
        name: YouTube
        domain: youtu.be
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
      author:
        - name: Piotr Talalay
          url: 'https://www.youtube.com/user/talalife'
          avatar: {}
      starred: false
      description: Live at The Worker And The Kolkhoz Woman. August 2015
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
